env:
  es6: true
  node: true

extends:
  - eslint:recommended

parser: "babel-eslint"
parserOptions:
  ecmaVersion: 8
  sourceType: module
  allowImportExportEverywhere: false
plugins:
  - babel
  - import
rules:
  strict: 0
  no-var: 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  no-console:
    - 0
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  import/no-unresolved: 2
  import/prefer-default-export: 2
  import/named: 2
globals:
  process: true
  window: true
  document: true
  console: true
  __dirname: true
  require: true
  module: true
  FB: true
  heap: true
  Buffer: true
  global: true
